import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowUpRight } from '../components/ArrowUpRight'
import { BrandLogo } from '../components/BrandLogo'
import { Header } from '../components/Header'
import { projects as allProjects } from '../data/portfolio'

const experiences = [
  { role: 'Software Developer Intern', company: 'NBS Private Limited', duration: '1 Month', description: 'Gained practical exposure to software development workflows, application development, debugging, and development practices.', skills: ['Software Development', 'Application Development', 'Debugging', 'Development Workflow'] },
  { role: 'Automation Testing Intern', company: 'Astraval', duration: '1 Month', description: 'Worked on automation testing activities and gained practical knowledge of software testing, test automation, debugging, and quality assurance workflows.', skills: ['Automation Testing', 'Software Testing', 'Test Automation', 'Debugging', 'QA Workflow'] },
  { role: 'Full Stack Developer Intern', company: 'This AI Technology Company', duration: '3 Months', description: 'Gained practical experience in frontend development, backend development, databases, application development, and full-stack workflows.', skills: ['Frontend Development', 'Backend Development', 'Database', 'Full Stack Development', 'Application Development'] },
]

const skillGroups = [
  ['Frontend Development', ['HTML', 'CSS', 'JavaScript', 'React']], ['Programming', ['Java', 'Python']], ['Backend Development', ['Django', 'Spring Boot']], ['Database', ['MongoDB', 'MySQL', 'PostgreSQL']], ['Mobile Development', ['Flutter', 'Android Studio']], ['Version Control', ['Git', 'GitHub']], ['Cloud & Deployment', ['AWS', 'Server Management', 'Deployment']],
]
const stack = ['HTML', 'CSS', 'JavaScript', 'Python', 'Java', 'React', 'Django', 'Spring Boot', 'MongoDB', 'MySQL', 'PostgreSQL', 'Flutter', 'Android Studio', 'Git', 'GitHub', 'AWS']
const services = [['Software Development', 'Building clean and maintainable software applications.'], ['Full Stack Development', 'Developing frontend and backend applications.'], ['Web Development', 'Creating responsive and modern websites.'], ['Automation Testing', 'Working with software testing and automation workflows.'], ['Database Development', 'Working with SQL and NoSQL databases.'], ['Cloud & Deployment', 'Working with AWS, servers, and application deployment.']]

function useReveal() { useEffect(() => { const nodes = document.querySelectorAll('.reveal-on-scroll'); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target) } }), { threshold: .12 }); nodes.forEach((node) => observer.observe(node)); return () => observer.disconnect() }, []) }
function Icon({ name }) { const common = { fill: 'none', stroke: 'currentColor', strokeWidth: 1.7, strokeLinecap: 'round', strokeLinejoin: 'round' }; const shapes = { code: <><path {...common} d="m8 9-3 3 3 3M16 9l3 3-3 3M14 6l-4 12" /></>, database: <><ellipse {...common} cx="12" cy="5" rx="7" ry="3" /><path {...common} d="M5 5v7c0 1.7 3.1 3 7 3s7-1.3 7-3V5M5 12v7c0 1.7 3.1 3 7 3s7-1.3 7-3v-7" /></>, mobile: <rect {...common} x="7" y="3" width="10" height="18" rx="2" />, cloud: <path {...common} d="M7 18h10a4 4 0 0 0 .4-8A5.5 5.5 0 0 0 7 8.5 4.7 4.7 0 0 0 7 18Z" /> }; return <svg viewBox="0 0 24 24" aria-hidden="true">{shapes[name] || shapes.code}</svg> }
function SocialIcon({ name }) { const common = { fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round', strokeLinejoin: 'round' }; const shapes = { LinkedIn: <><path {...common} d="M6 9v9M6 6v.01M10 18v-5a4 4 0 0 1 8 0v5M10 13v5" /></>, GitHub: <><path {...common} d="M9 19c-5 .9-5-2.5-7-3m14 6v-3.9a3.4 3.4 0 0 0-.9-2.6c3-.3 6.2-1.5 6.2-6.8A5.3 5.3 0 0 0 20 5.1 5 5 0 0 0 19.9 1S18.7.7 16 2.5a13.4 13.4 0 0 0-7 0C6.3.7 5.1 1 5.1 1A5 5 0 0 0 5 5.1a5.3 5.3 0 0 0-1.4 3.6c0 5.3 3.2 6.5 6.2 6.8A3.4 3.4 0 0 0 9 18.1V22" /></>, Instagram: <><rect {...common} x="3" y="3" width="18" height="18" rx="5" /><circle {...common} cx="12" cy="12" r="4" /><path {...common} d="M17.5 6.5h.01" /></> }; return <svg viewBox="0 0 24 24" aria-hidden="true">{shapes[name]}</svg> }
function TechIcon({ name, mark, index }) { return <div className={`hero-tech hero-tech-${index}`} style={{ '--tech': mark.color }} tabIndex="0"><span className="tech-tooltip">{name}</span><b>{mark.icon}</b></div> }
function ProjectVisual({ project }) { return <div className={`project-visual project-${project.visual}`} aria-label={`${project.title} preview`}><img src={project.image} alt="" loading="lazy" /><span className="visual-window"><i /><i /><i /></span><b>{project.number}</b></div> }
function SectionTitle({ kicker, title, text }) { return <div className="section-title reveal-on-scroll"><p>{kicker}</p><h2>{title}</h2>{text && <span>{text}</span>}</div> }
function ContactForm() { const [values, setValues] = useState({ name: '', email: '', message: '' }); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const submit = (event) => { event.preventDefault(); if (!values.name.trim() || !values.email.trim() || !values.message.trim()) { setError('Please complete your name, email, and message.'); return } if (!/^\S+@\S+\.\S+$/.test(values.email)) { setError('Please enter a valid email address.'); return } setError(''); setSent(true) }; return <form className="contact-form reveal-on-scroll" onSubmit={submit} noValidate>{['name', 'email'].map((field) => <label key={field}>{field === 'name' ? 'Name' : 'Email'}<input type={field === 'email' ? 'email' : 'text'} value={values[field]} onChange={(event) => setValues({ ...values, [field]: event.target.value })} /></label>)}<label>Message<textarea rows="5" value={values.message} onChange={(event) => setValues({ ...values, message: event.target.value })} /></label>{error && <p className="form-error" role="alert">{error}</p>}{sent && <p className="form-success" role="status">Thanks — your message is ready to send.</p>}<button className="button primary" type="submit">Send Message <ArrowUpRight /></button></form> }

export function HomePage() { useReveal(); const heroTech = [{ name: 'Java', icon: 'J', color: '#ef6c36' }, { name: 'Python', icon: 'Py', color: '#4a94cf' }, { name: 'JavaScript', icon: 'JS', color: '#e6c54a' }, { name: 'React', icon: '⚛', color: '#62d8ef' }, { name: 'Flutter', icon: 'F', color: '#4b9fe8' }, { name: 'Git', icon: '◆', color: '#e36b4b' }, { name: 'AWS', icon: 'aws', color: '#dca44c' }, { name: 'MongoDB', icon: 'M', color: '#62ae72' }]; const roles = ['Software Developer', 'Full Stack Developer', 'AI & IoT Enthusiast']; const [roleIndex, setRoleIndex] = useState(0); const navigate = useNavigate(); const visibleProjects = allProjects.slice(0, 3); useEffect(() => { const timer = window.setInterval(() => setRoleIndex((index) => (index + 1) % roles.length), 2600); return () => window.clearInterval(timer) }, []); return <main className="rahul-portfolio"><Header />
  <section id="home" className="rp-hero rp-hero-programming"><div className="hero-copy reveal-on-scroll"><p className="kicker hero-text hero-text-1">Hello, I&apos;m</p><h1 className="hero-text hero-text-2">RAHUL</h1><h3 className="hero-text hero-text-3">B.Tech CSE (AI & IoT) Student</h3><p className="role-lines hero-text hero-text-4"><b key={roles[roleIndex]}>{roles[roleIndex]}</b></p><span className="hero-text hero-text-5">I build modern software applications and explore full-stack development, automation, cloud, databases, and AI & IoT technologies.</span><nav className="hero-socials hero-text hero-text-6" aria-label="Social profiles"><a href="https://github.com/codeofrealm" target="_blank" rel="noreferrer" aria-label="GitHub"><SocialIcon name="GitHub" /></a><a href="https://www.linkedin.com/in/rahul-77a46b273?utm_source=share_via&utm_content=profile&utm_medium=member_android" target="_blank" rel="noreferrer" aria-label="LinkedIn"><SocialIcon name="LinkedIn" /></a><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon name="Instagram" /></a></nav></div><div className="hero-dev-visual reveal-on-scroll" aria-label="Programming technologies" onPointerMove={(event) => { const box = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty('--move-x', `${((event.clientX - box.left) / box.width - .5) * 6}px`); event.currentTarget.style.setProperty('--move-y', `${((event.clientY - box.top) / box.height - .5) * 6}px`) }} onPointerLeave={(event) => { event.currentTarget.style.setProperty('--move-x', '0px'); event.currentTarget.style.setProperty('--move-y', '0px') }}><div className="code-editor"><header><i /><i /><i /><span>rahul.dev</span></header><pre><em>class</em> Rahul {'{'}{`\n`}  <b>String</b> role = <strong>"Developer"</strong>;{`\n\n`}  <em>void</em> build() {'{'}{`\n`}    learn();{`\n`}    create();{`\n`}    innovate();{`\n`}  {'}'}{`\n`}{'}'}</pre></div>{heroTech.map((tech, index) => <TechIcon key={tech.name} name={tech.name} mark={tech} index={index} />)}<div className="hero-facts"><div><b>12+</b><span>Projects</span></div><div><b>3</b><span>Internships</span></div><div><b>CSE</b><span>AI & IoT</span></div><div><b>B.Tech</b><span>Student</span></div></div></div><a className="scroll-explore" href="#about"><span>Scroll to explore</span><i /></a></section>
  <section id="about" className="rp-section"><SectionTitle kicker="01 / About" title="About Me" text="Building a practical foundation in software development." /><div className="about-layout reveal-on-scroll"><p>I am Rahul, a B.Tech Computer Science Engineering student specializing in Artificial Intelligence and IoT. I am interested in software development, full-stack development, automation testing, cloud technologies, and modern application development.</p><p>I have completed 12+ projects and gained practical industry exposure through three internships. These experiences helped me understand real-world software development, testing, web technologies, and application development.</p></div><div className="info-cards">{['12+ Projects', '3 Internships', 'B.Tech CSE (AI & IoT)', 'Software Development'].map((item, index) => <article className="reveal-on-scroll" style={{ '--delay': `${index * 80}ms` }} key={item}>{item}</article>)}</div></section>
  <section id="experience" className="rp-section section-muted"><SectionTitle kicker="02 / Experience" title="Experience" text="Internship & Industry Experience" /><div className="timeline">{experiences.map((item, index) => <article className={`timeline-card reveal-on-scroll ${index % 2 ? 'from-right' : 'from-left'}`} style={{ '--delay': `${index * 100}ms` }} key={item.company}><i>0{index + 1}</i><div><p>{item.duration}</p><h3>{item.role}</h3><b>{item.company}</b><span>{item.description}</span><ul>{item.skills.map((skill) => <li key={skill}>{skill}</li>)}</ul></div></article>)}</div></section>
  <section id="skills" className="rp-section"><SectionTitle kicker="03 / Skills" title="Technical Skills" text="A practical development toolkit." /><div className="skill-groups">{skillGroups.map(([group, items], index) => <article className="reveal-on-scroll" style={{ '--delay': `${index * 60}ms` }} key={group}><Icon name={index === 3 ? 'database' : index === 4 ? 'mobile' : index === 6 ? 'cloud' : 'code'} /><h3>{group}</h3><div>{items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
  <section id="projects" className="rp-section section-muted"><SectionTitle kicker="04 / Projects" title="Featured Projects" text="Selected work across full-stack development, mobile, data, and AI." /><div className="project-grid">{visibleProjects.map((project, index) => <article className="project-card reveal-on-scroll" style={{ '--delay': `${index * 100}ms` }} key={project.number}><ProjectVisual project={project} /><div><p>{project.category}</p><h3>{project.title}</h3><span>{project.description}</span><ul className="project-tech">{project.tech.map((item) => <li key={item}>{item}</li>)}</ul><footer>{project.github ? <a href={project.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight /></a> : <a href="#contact">Request details <ArrowUpRight /></a>}</footer></div></article>)}</div><div style={{textAlign:'center',marginTop:'2.5rem'}}><button className="button primary" onClick={() => navigate('/projects')}>View All Projects <ArrowUpRight /></button></div></section>
  <section className="rp-stats"><article className="reveal-on-scroll"><b>12+</b><span>Projects</span></article><article className="reveal-on-scroll"><b>3</b><span>Internships</span></article><article className="reveal-on-scroll"><b>Multiple</b><span>Technologies</span></article><article className="reveal-on-scroll"><b>B.Tech</b><span>CSE (AI & IoT)</span></article></section>
  <section id="education" className="rp-section"><SectionTitle kicker="05 / Education" title="Education" /><article className="education-card reveal-on-scroll"><p>B.Tech</p><div><h3>Computer Science Engineering</h3><span>Specialization: Artificial Intelligence & IoT</span></div><ul><li>Degree: B.Tech</li><li>Department: Computer Science Engineering</li><li>Specialization: AI & IoT</li><li>Status: Student</li></ul></article></section>
  <section className="rp-section section-muted"><SectionTitle kicker="06 / Technology Stack" title="Technologies I Work With" /><div className="tech-grid">{stack.map((item, index) => <article className="reveal-on-scroll" style={{ '--delay': `${(index % 8) * 45}ms` }} key={item}><Icon name="code" /><span>{item}</span></article>)}</div></section>
  <section className="rp-section"><SectionTitle kicker="07 / Services" title="What I Can Do" /><div className="service-grid">{services.map(([title, text], index) => <article className="reveal-on-scroll" style={{ '--delay': `${index * 70}ms` }} key={title}><i>0{index + 1}</i><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section id="contact" className="rp-contact"><div><SectionTitle kicker="08 / Contact" title="Let&apos;s Connect" text="I&apos;m always interested in learning, building new projects, and connecting with people in technology." /><div className="contact-info reveal-on-scroll"><span>Email <b><a href="mailto:rahul63794@gmail.com">rahul63794@gmail.com</a></b></span><span>Phone <b>Add Phone</b></span><span>GitHub <b><a href="https://github.com/codeofrealm" target="_blank" rel="noreferrer">codeofrealm</a></b></span><span>LinkedIn <b><a href="https://www.linkedin.com/in/rahul-77a46b273?utm_source=share_via&utm_content=profile&utm_medium=member_android" target="_blank" rel="noreferrer">Rahul</a></b></span></div></div><ContactForm /></section>
  <footer className="rp-footer"><div><BrandLogo className="h-8 w-8" /><b>RAHUL</b></div><span>B.Tech CSE (AI & IoT) Student</span><span className="footer-socials"><a href="https://github.com/codeofrealm" target="_blank" rel="noreferrer">GitHub</a> · <a href="https://www.linkedin.com/in/rahul-77a46b273?utm_source=share_via&utm_content=profile&utm_medium=member_android" target="_blank" rel="noreferrer">LinkedIn</a> · <a href="mailto:rahul63794@gmail.com">Email</a></span><span>© 2026 Rahul. All Rights Reserved.</span></footer>
</main> }
